//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridgeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Iname { get; set; }
        public string Idescription { get; set; }
        public int Iprice { get; set; }
        public System.DateTime IaddDate { get; set; }
        public Nullable<System.DateTime> IexpDate { get; set; }
        public string Iavailable { get; set; }
    }
}
