//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ShopBridgeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iuser
    {
        public int Uid { get; set; }
        [Required]
        public string Uemail { get; set; }
        [Required]
        public string Upass { get; set; }
        [Required]
        public short Urole { get; set; }
    }
}
